version: '3.7'

services:
    mysql:
        image: mysql:8.0
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: on-failure
        volumes:
            - '.:/usr/src/app:cached'

    nginx:
        image: nginx:1.15.3-alpine
        restart: on-failure
        volumes:
            - './public/:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '8083:80'
        depends_on:
            - php
    adminer:
        image: adminer
        restart: on-failure
        ports:
            - '8084:8080'